services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan migrate --force
      php artisan db:seed --force
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d13ringgjchc73fg4vt0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: kas_kelas_p07k
      - key: DB_USERNAME
        value: kas
      - key: DB_PASSWORD
        fromService:
          name: kas_kelas
          property: password