services:
  - type: web
    name: kas-kelasssss
    runtime: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      # tambahin APP_KEY, DB_*, dll di dashboard atau langsung di sini

    port: 10000