services:
  - type: web
    name: kas_kelas
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: |
      php artisan migrate --force && \
      php artisan db:seed --force && \
      apache2-foreground
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d13ringgjchc73fg4vt0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: kas_kelas_p07k
      - key: DB_USERNAME
        value: kas
      - key: DB_PASSWORD
        value: UmRBJ1fn3cE7ueTu7ly3lP5cR8nUMt8l

# Optional: define DB kalau lo mau pake `fromDatabase`
# databases:
#   - name: kas_kelas_db
#     databaseName: kas_kelas_p07k
#     user: kas
#     plan: free
